### ISSUE TITLE
Add support for true Calls & Call inlining

### ISSUE THREAD

**Issue by pjattke** [MarbleHE/HECO#12]
## Adding support for proper calls
Currently, the AST Call node is only used for "fake" calls like rotate. However, in general it would be nice to support real functions and calls.

## Add inling
In v1.0, we supported function inlining, up to a certain threshold. This feature should be ported over.

## Adding Tests:

In v1.0, Commit 97c1679397 added a threshold to the inlining of `Call` nodes, i.e., functions are only inlined if their return statement has a depth smaller than _N_ nodes. 

- There exist no tests yet that check if that threshold really works. 

- Also, there must be an additional check added that makes sure that the called function is fully inlined, that is, there are not other statements in the program except a `Return` statement. Because otherwise replacing only the function call by the return expression in the called function would lead to an invalid result.

**Comment by AlexanderViand-Intel** [comment]
Closing this issue as it concerns the legacy version of HECO (pre-MLIR)
