### ISSUE TITLE
Annotations for nullability of attributes

### ISSUE THREAD

**Issue by pjattke** [MarbleHE/HECO#20]
Currently, it is not obvious which AST node attributes are mandatory and which are optional. For example, an `If` statement optionally takes an initializer and an update statement but requires a condition and a body statement. 

We therefore should introduce a system to denote attributes as nullable/non-nullable, for example, using [Clang's annotation feature](https://clang.llvm.org/docs/analyzer/developer-docs/nullability.html) that also throws warnings at compile-time. We should check in advance if these annotations are also supported by the other compilers (MSVC, gcc).

**Comment by AlexanderViand-Intel** [comment]
Closing this issue as the ABC AST classes are no longer used in the current MLIR-only HECO.
