### ISSUE TITLE
Python Frontend Limitations

### ISSUE THREAD

**Issue by Miro-H** [MarbleHE/HECO#36]
# Python Frontend Limitations

This issue tracks the current limitations of the Python frontend. Some of them are simply not implemented, others have more fundamental issues.

### Reduced Syntax

Python has quite a rich syntax. Check `python/pyabc/ABCVisitor.py` to see which constructs are supported and which are not.

### Multi-Assignment
This could be supported with our current AST, but would require us to build the JSON string manually in the Python frontend instead of building a dictionary. Manual building would allow one visit function to add more than one statement to the resulting string.

Alternatively, support for multi-assignments can be added to the AST. IMO, this would be a cleaner solution.

## Float vs. Double
We just convert every decimal number (`float` in Python) to a `double` in C++.  Keep in mind that the FHE circuit only does approximate computation on floats anyway, so such computations lose some precision even if the types could be preserved.

## Dynamic Types

Variables cannot change their types (neither in C++ nor our FHE AST). Translations with an IR or to SSA would solve this issue.

## Type Casting

The frontend does not support type casting. I.e., `double * int` will result in an error and not implicitly cast the `int` to a `double`. ABC does not support this either.

For this reason, the frontend currently simply parses the value of a variable declaration and then uses the data type of the first constant that it finds among those values. For a list, it takes the type of the first entry, as in ABC, all values are vectors, so a vector of `LiteralInt` also has type `LiteralInt`.

:warning: An unexpected side-effect of this is, that the Python operator `/` behaves like `//` for Integers. The Python expression `(2 * 6) / 5` would return `2.4` in Python, but returns `2` for our FHE program, since it is integer division and no type casting happens.

## Returning expressions

Currently, a function has to return a variable and cannot return expressions. This is because the RuntimeVisitor requires a list of variables which should be returned in the end.

This is no fundamental limitation. Either the frontend parsing could introduce one variable for every returned expression, or the RuntimeVisitor could be changed to support non-variable return values. ABC AST Return nodes do support arbitrary AbstractExpression's to be returned.

## Multiple Return Statements
Multiple return statements are currently not really supported. The ABC AST can return `ExpressionList` variables, but we currently use them to represent Python lists so we cannot use them for multi-return values (of the same type) as well. In Python, multi-return statements have a `Tuple` argument, which we don't support (see also #37).

Note that the frontend code would already be written in a way that would support multiple return values.

### Mixed Return Types or Lists

We do not support returning different types, i.e.:
```Python
return 1, "abc" # not supported
```

The `execute` function of the Python wrapper supports some hackery to be able to return different literal types (casted to Python types). For this purpose, it is declared to return a Python object instead of a specific C++ type, so that it can return different values and lists. However, multi-return statements are currently not supported because they cannot be parsed. Returning the values would be possible using similar tricks.

## For Loops Only Support Range
For loops currently only support iterating over a `range`. This construct only does addition/subtraction. The Pythonic way to do more complex conditions is usually to use while loops, but we do not yet support while loops.

Be aware, that the Python expression 
```Python
for i in range(a, b, s)
```
is translated to the condition:
```Cpp
for(int i = a; ((a <= b) && i < b) || ((a > b) && i > b); i += s)
```
because `s` can be negative.

Like Python, for `range(b)` we use  `a = 0` and `s = 1`, and for `range(a, b)` we use `s = 1`.

At the moment, we just force the loop variable of for-loops to be an `int`.

## Variable Types

:warning: Type information on a variable gets lost when you declare a new variable to equal another one.
The problem is that at compile-time, we do not know the type of all variables in Python. For function arguments, the variable type is not known. We could solve this in the future by requiring type annotation for those values. The consequence is currently that variables always have to be set to literal types or expressions (without abstract targets).

The issue with "void"-type variables is, that we cannot operate on them. E.g., to compare them with other integers or do arithmetic. Or we would need to figure out the type when we perform an operation, but then it could change depending on the operation.

For example, the following works:
```Python
def main(a):
    r = a + 1
    return r
```
But not this, since `b` is of type `void`, which cannot be added with a `LiteralInt`:
```Python
def main(a):
    b = a
    r = a + 1
    return r
```
However, this would work if we know that `a` is always an `int`:
```Python
def main(a):
    b = 0
    b = a
    r = a + 1
    return r
```

## Python Lists =/= `ExpressionList`s
At the moment, Python lists are translated to ABC ExpressionLists. We potentially need to give up some list features if we keep them like this (list comprehension, list concatenation).

## Ciphertext Results
Currently, we only support the `DummyCiphertextFactory`. There is no way to export encrypted data to Python. We therefore always decrypt it and then return it. Only `vector<int64_t>` results are supported by the `DummyCiphertextFactory`.

## Known Bug: Secret Tainting Return Values
There is a bug when we define and return a new variable that is tainted.

The following throws an error:
```Cpp
def main(a, b):
  r = a + b
  return r
```
Error: ` RuntimeError: Initialization value of VariableDeclaration ( r) could not be processed successfully.`

However, using an input variable to store the output is a workaround:
```Cpp
def main(a, b):
  a += b
  return a
```

## Ineractive Console
The frontend does not work on an interactive console (e.g., when executing `python` on the command line), since it cannot fetch the source code.

## Return Ciphertext
At the moment, it is not possible to get the result of a function with secret inputs. The reason is that we don't have a wrapper for the serialized ciphertext and its context information.

As a temporary hack, we only use the `DummyCiphertext` suite and always decrypt results before returning them.

## External Function Calls with Non-Secret Inputs
External function calls with non-secret inputs may return unexpected results. E.g., when the function branches based on an unknown input, then the translation can lead to unexpected result, since the condition is executed on a generic ciphertext object.
The underlying problem is that we don't explore all possible execution paths, since they depend on the unknown input. This is not an issue for secret inputs, since we cannot branch on them anyway. However, it also doesn't work for non-secret inputs, since we do not distinguish them and replace both with generic objects.

**Comment by AlexanderViand-Intel** [comment]
Closing issue about limitations of the old Python frontend.
