### ISSUE TITLE
Building HECO

### ISSUE THREAD

**Issue by or-cr** [MarbleHE/HECO#45]
Hello,

I've noticed that branch `main` isn't really HECO, so I've tried to build `dev`.
After building SEAL and MLIR as required, the command `cmake --build . --target check-fhe` as written in the README doesn't work (no such target).
Which target should I build? Is `dev` even the correct branch to work with?

Thanks,
Or

**Comment by AlexanderViand** [comment]
Thanks for the PR, which I just merged :) 

You should not be getting that error message from the examples, that's definitively a bug somewhere (either in the example or one of the passes before tensor2fhe). Actually, give me a day to have a look at this, I'm sure I can get things cleaned up enough to run examples & play around, even with some other changes/etc still pending :)

**Comment by or-cr** [comment]
Cool, thanks

**Comment by or-cr** [comment]
Cool, it works :)
Thanks!
