### ISSUE TITLE
Overwriting secret variable by public value

### ISSUE THREAD

**Issue by pjattke** [MarbleHE/HECO#5]
Overwriting a secret variable by a public value on **all execution paths** lets the variable become public. See TODO note in SecretTaintingVisitor class.

Use the ControlFlowGraphVisitor to determine the execution paths and the generated data flow graph to analyze if a variable is written in all of these paths and if the written value is public.

**Comment by AlexanderViand** [comment]
In v2.0, the secret tainting code has moved to the TypeCheckingVisitor. However, it is still "strict" in the sense of ignoring when a secret value has been overwritten with a public one.

**Comment by AlexanderViand-Intel** [comment]
Closing this issue as in "v3.0", aka the current MLIR-based HECO, this is now a concern for the frontend rather than the compiler.
