### ISSUE TITLE
Extend special function calls from rotate to ctxt maintenance operations

### ISSUE THREAD

**Issue by pjattke** [MarbleHE/HECO#7]
The current AST implementation does not support common FHE operations such as ModSwitch, Relinearization, and Key-Switching. These operations must be added as simple placeholders (without logic). 

Maybe it makes sense to introduce a general node that does not contain any implementation but serves as placeholder? It could have an attribute "operation type" that designates the operation it stands for, e.g., ModSwitch.

**Comment by AlexanderViand** [comment]
In v2.0 this kind of thing is done using the "Call" AST node for rotations, so it'd be natural to extend this idea to the ctxt maintenance operations
